# Generated by Django 4.2.4 on 2023-08-11 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages='name field is required.', max_length=64)),
                ('description', models.TextField(default='', error_messages='description is optional and default value is empty string.')),
                ('price', models.FloatField(error_messages='price is required and float. Minimum value is 0.00 and default value is 0.00.', validators=[django.core.validators.MinValueValidator(limit_value=0.0)])),
            ],
        ),
    ]
